version: '3.8'
services:
  db:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
