name: base
channels:
  - defaults
dependencies:
  - python
  - black
  - pylint
  - mock
  - pytest
  - ipython
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - plotly
  - seaborn
  - jupyter
  - flask
  #- beautifulsoup3
