# example profiles.yml file
adventure_works:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: Adventureworks
      schema: analytics
      threads: 4
    prod:
      type: postgres
      host:
      user:
      password:
      port:
      dbname:
      schema:
      threads: 4
